# Generated by Django 4.2.6 on 2023-11-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_channel_name_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.IntegerField(default=0, verbose_name='Подписчиков'),
        ),
        migrations.AddField(
            model_name='channel',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
