# Generated by Django 4.2.6 on 2023-11-08 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='services',
        ),
        migrations.AddField(
            model_name='tariff',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='upload/', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='system_id',
            field=models.IntegerField(default=0, verbose_name='Id накрутки'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
