# Generated by Django 4.2.6 on 2023-11-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('facebook', 'FaceBook'), ('wasd', 'WASD.TV'), ('trovo', 'Trovo'), ('tiktok', 'TikTok')], max_length=100, verbose_name='Тип сервиса'),
        ),
    ]
