# Generated by Django 4.2.6 on 2023-11-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='type_service',
        ),
    ]
