# Generated by Django 4.2.6 on 2023-11-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_type_service_type_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type_service',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('facebook', 'FaceBook'), ('wasd', 'WASD.TV'), ('trovo', 'Trovo'), ('tiktok', 'TikTok')], verbose_name='Тип сервиса'),
        ),
    ]
