# Generated by Django 4.2.6 on 2023-11-04 08:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('phrases', models.TextField(verbose_name='Фразы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фразы для чатов',
                'verbose_name_plural': 'Фразы для чатов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_bots', models.IntegerField(default=0, verbose_name='Количество ботов')),
                ('count_minutes', models.IntegerField(default=0, verbose_name='Количество минут')),
                ('price', models.IntegerField(blank=True, verbose_name='Стоимость')),
                ('login_bot', models.CharField(blank=True, default=0, verbose_name='Логин бота')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('pause', 'Пауза'), ('success', 'Успех'), ('error', 'Ошибка')], default='active', max_length=20, verbose_name='Статус заказа')),
                ('interval_from', models.IntegerField(default=0, verbose_name='Интервал между сообщениями (От)')),
                ('interval_to', models.IntegerField(default=1, verbose_name='Интервал между сообщениями (До)')),
                ('bot_volume', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Объём охвата чат-ботов')),
                ('chat_bot_mode', models.CharField(choices=[('random', 'Случайно'), ('start', 'С начала'), ('end', 'С конца')], default='random', max_length=10, verbose_name='Режим чата')),
                ('send_interval_from', models.IntegerField(default=0, verbose_name='Интервал отправки (от)')),
                ('send_interval_to', models.IntegerField(default=0, verbose_name='Интервал отправки (до)')),
                ('dictionary', models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='Словарь')),
                ('auto_start_chat', models.BooleanField(default=False, verbose_name='Автозапуска чата')),
                ('endless_messages', models.BooleanField(default=False, verbose_name='Бесконечные сообщения')),
                ('viewer_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество зрителей')),
                ('auto_start_viewer', models.BooleanField(default=False, verbose_name='Активация автозапуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('auto_greeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs_auto_greeting', to='orders.phrasegroup', verbose_name='Автоматическое приветствие группа (группа фраз)')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.channel', verbose_name='Канал')),
                ('mass_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs_mass_message', to='orders.phrasegroup', verbose_name='Массовое сообщение (группа фраз)')),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказы пользователей',
                'verbose_name_plural': 'Заказы пользователей',
            },
        ),
    ]
